// automatically generated by the FlatBuffers compiler, do not modify

// NOLINTBEGIN

#ifndef FLATBUFFERS_GENERATED_EXAMPLES_APOLLO_CYBER_EXAMPLES_PROTO_H_
#define FLATBUFFERS_GENERATED_EXAMPLES_APOLLO_CYBER_EXAMPLES_PROTO_H_

#include "flatbuffers/flatbuffers.h"

namespace apollo {
namespace cyber {
namespace examples {
namespace proto {

struct Chatter;
struct ChatterBuilder;

struct Chatter FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ChatterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_LIDAR_TIMESTAMP = 6,
    VT_SEQ = 8,
    VT_CONTENT = 10
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint64_t lidar_timestamp() const {
    return GetField<uint64_t>(VT_LIDAR_TIMESTAMP, 0);
  }
  uint64_t seq() const {
    return GetField<uint64_t>(VT_SEQ, 0);
  }
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_LIDAR_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_SEQ, 8) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           verifier.EndTable();
  }
};

struct ChatterBuilder {
  typedef Chatter Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Chatter::VT_TIMESTAMP, timestamp, 0);
  }
  void add_lidar_timestamp(uint64_t lidar_timestamp) {
    fbb_.AddElement<uint64_t>(Chatter::VT_LIDAR_TIMESTAMP, lidar_timestamp, 0);
  }
  void add_seq(uint64_t seq) {
    fbb_.AddElement<uint64_t>(Chatter::VT_SEQ, seq, 0);
  }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(Chatter::VT_CONTENT, content);
  }
  explicit ChatterBuilder(flatbuffers::FlatBufferBuilder &_fbb)
      : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Chatter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Chatter>(end);
    return o;
  }
};

inline flatbuffers::Offset<Chatter> CreateChatter(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint64_t lidar_timestamp = 0,
    uint64_t seq = 0,
    flatbuffers::Offset<flatbuffers::String> content = 0) {
  ChatterBuilder builder_(_fbb);
  builder_.add_seq(seq);
  builder_.add_lidar_timestamp(lidar_timestamp);
  builder_.add_timestamp(timestamp);
  builder_.add_content(content);
  return builder_.Finish();
}

inline flatbuffers::Offset<Chatter> CreateChatterDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint64_t lidar_timestamp = 0,
    uint64_t seq = 0,
    const char *content = nullptr) {
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return apollo::cyber::examples::proto::CreateChatter(
      _fbb,
      timestamp,
      lidar_timestamp,
      seq,
      content__);
}

inline const apollo::cyber::examples::proto::Chatter *GetChatter(
    const void *buf) {
  return flatbuffers::GetRoot<apollo::cyber::examples::proto::Chatter>(buf);
}

inline const apollo::cyber::examples::proto::Chatter *GetSizePrefixedChatter(
    const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<
      apollo::cyber::examples::proto::Chatter>(buf);
}

inline bool VerifyChatterBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<apollo::cyber::examples::proto::Chatter>(
      nullptr);
}

inline bool VerifySizePrefixedChatterBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<
      apollo::cyber::examples::proto::Chatter>(nullptr);
}

inline void FinishChatterBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<apollo::cyber::examples::proto::Chatter> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedChatterBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<apollo::cyber::examples::proto::Chatter> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace proto
}  // namespace examples
}  // namespace cyber
}  // namespace apollo

// NOLINTEND

#endif  // FLATBUFFERS_GENERATED_EXAMPLES_APOLLO_CYBER_EXAMPLES_PROTO_H_
