services:
  cyber-dev:
    build:
      context: ..
      dockerfile: docker/dev.x86_64.dockerfile
    container_name: ubuntu2204
    image: cyber-core:latest

    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"

    environment:
      - HOST_USER=${HOST_USER:-developer}
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - HOME=/home/${HOST_USER:-developer}
      
    volumes:
      - ..:/workspace
      - ${BAZEL_CACHE:-/tmp/bazel-apollo-docker}:/home/${HOST_USER:-developer}/.cache/bazel
      - ${PASSWD_FILE:-/tmp/wheelos-docker-passwd}:/etc/passwd:ro
      - ${GROUP_FILE:-/tmp/wheelos-docker-group}:/etc/group:ro
      
    working_dir: /workspace
    ipc: private
    network_mode: host
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
    restart: unless-stopped
