load("@rules_cc//cc:defs.bzl", "cc_library")


package(default_visibility = ["//visibility:public"])

cc_library(
    name = "gnss_util",
    srcs = [],
    hdrs = [
        "macros.h",
        "time_conversion.h",
    ],
)


