package(default_visibility = ["//visibility:public"])

alias(
    name = "mainboard",
    actual = "//cyber/mainboard:mainboard",
)

alias(
    name = "cyber_launch",
    actual = "//cyber/tools/cyber_launch:cyber_launch",
)

alias(
    name = "cyber_recorder",
    actual = "//cyber/tools/cyber_recorder:cyber_recorder",
)

alias(
    name = "cyber_monitor",
    actual = "//cyber/tools/cyber_monitor:cyber_monitor",
)

alias(
    name = "cyber_channel",
    actual = "//cyber/tools/cyber_channel:cyber_channel",
)

alias(
    name = "cyber_node",
    actual = "//cyber/tools/cyber_node:cyber_node",
)

alias(
    name = "cyber_service",
    actual = "//cyber/tools/cyber_service:cyber_service",
)
