/******************************************************************************
 * Copyright 2019 The Apollo Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************/

/* note that the frame code of the following is Generated by script  */

#include "cyber/timer/timer.h"

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <future>
#include <memory>
#include <mutex>
#include <thread>
#include <utility>

#include "gtest/gtest.h"

#include "cyber/common/util.h"
#include "cyber/cyber.h"
#include "cyber/init.h"
#include "cyber/proto/unit_test.pb.h"

namespace apollo {
namespace cyber {
namespace timer {

using cyber::Timer;
using cyber::TimerOption;

TEST(TimerTest, one_shot) {
  int count = 0;
  Timer timer(
      100, [&count] { count = 100; }, true);
  timer.Start();
  std::this_thread::sleep_for(std::chrono::milliseconds(90));
  EXPECT_EQ(0, count);
  // Here we need to consider the scheduling delay, up to 500ms, make sure the
  // unit test passes.
  std::this_thread::sleep_for(std::chrono::milliseconds(500));
  EXPECT_EQ(100, count);
  timer.Stop();
}

TEST(TimerTest, cycle) {
  using TimerPtr = std::shared_ptr<Timer>;
  int count = 0;
  TimerPtr timers[1000];
  TimerOption opt;
  opt.oneshot = false;
  opt.callback = [=] { AINFO << count; };
  for (int i = 0; i < 1000; i++) {
    opt.period = i + 1;
    timers[i] = std::make_shared<Timer>();
    timers[i]->SetTimerOption(opt);
    timers[i]->Start();
  }

  std::this_thread::sleep_for(std::chrono::seconds(3));
  for (int i = 0; i < 1000; i++) {
    timers[i]->Stop();
  }
}

TEST(TimerTest, start_stop) {
  int count = 0;
  Timer timer(
      2, [count] { AINFO << count; }, false);
  for (int i = 0; i < 100; i++) {
    timer.Start();
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
    timer.Stop();
  }
}

TEST(TimerTest, concurrent_stop_and_restart) {
  std::atomic<int> callback_count{0};
  std::mutex callback_mutex;
  std::condition_variable callback_entered_cv;
  std::condition_variable release_callback_cv;
  bool first_callback_entered = false;
  bool release_first_callback = false;

  Timer timer(100,
              [&]() {
                const int count = callback_count.fetch_add(1) + 1;
                if (count != 1) {
                  return;
                }
                std::unique_lock<std::mutex> lock(callback_mutex);
                first_callback_entered = true;
                callback_entered_cv.notify_one();
                release_callback_cv.wait(
                    lock, [&release_first_callback]() {
                      return release_first_callback;
                    });
              },
              false);
  timer.Start();

  {
    std::unique_lock<std::mutex> lock(callback_mutex);
    ASSERT_TRUE(callback_entered_cv.wait_for(
        lock, std::chrono::seconds(5),
        [&first_callback_entered]() { return first_callback_entered; }));
  }

  auto stop_future = std::async(std::launch::async, [&timer]() { timer.Stop(); });
  EXPECT_EQ(stop_future.wait_for(std::chrono::milliseconds(20)),
            std::future_status::timeout);

  auto restart_future =
      std::async(std::launch::async, [&timer]() { timer.Start(); });
  EXPECT_EQ(restart_future.wait_for(std::chrono::seconds(1)),
            std::future_status::ready);

  {
    std::lock_guard<std::mutex> lock(callback_mutex);
    release_first_callback = true;
  }
  release_callback_cv.notify_one();

  EXPECT_EQ(stop_future.wait_for(std::chrono::seconds(5)),
            std::future_status::ready);

  const int restarted_count = callback_count.load(std::memory_order_acquire);
  const auto deadline =
      std::chrono::steady_clock::now() + std::chrono::seconds(2);
  while (std::chrono::steady_clock::now() < deadline &&
         callback_count.load(std::memory_order_acquire) == restarted_count) {
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
  }

  timer.Stop();
  EXPECT_GT(callback_count.load(std::memory_order_acquire), restarted_count);
}

TEST(TimerTest, callback_creates_message_subscription) {
  using proto::Chatter;

  const std::string suffix = std::to_string(Time::MonoTime().ToNanosecond());
  const std::string channel_name = "/timer/subscription_" + suffix;
  auto reader_node = CreateNode("timer_reader_" + suffix);
  auto writer_node = CreateNode("timer_writer_" + suffix);
  ASSERT_NE(nullptr, reader_node);
  ASSERT_NE(nullptr, writer_node);

  std::mutex reader_mutex;
  std::shared_ptr<Reader<Chatter>> reader;
  std::atomic<bool> reader_created{false};
  std::atomic<bool> message_received{false};
  Timer timer(
      10,
      [&]() {
        std::lock_guard<std::mutex> lock(reader_mutex);
        reader = reader_node->CreateReader<Chatter>(
            channel_name, [&](const std::shared_ptr<Chatter>& message) {
              if (message->content() == "timer callback subscription") {
                message_received.store(true, std::memory_order_release);
              }
            });
        reader_created.store(reader != nullptr, std::memory_order_release);
      },
      true);
  timer.Start();

  const auto reader_deadline =
      std::chrono::steady_clock::now() + std::chrono::seconds(5);
  while (!reader_created.load(std::memory_order_acquire) &&
         std::chrono::steady_clock::now() < reader_deadline) {
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
  }
  ASSERT_TRUE(reader_created.load(std::memory_order_acquire));

  auto writer = writer_node->CreateWriter<Chatter>(channel_name);
  ASSERT_NE(nullptr, writer);
  auto message = std::make_shared<Chatter>();
  message->set_content("timer callback subscription");
  const auto message_deadline =
      std::chrono::steady_clock::now() + std::chrono::seconds(5);
  while (!message_received.load(std::memory_order_acquire) &&
         std::chrono::steady_clock::now() < message_deadline) {
    ASSERT_TRUE(writer->Write(message));
    std::this_thread::sleep_for(std::chrono::milliseconds(20));
  }

  timer.Stop();
  EXPECT_TRUE(message_received.load(std::memory_order_acquire));
}

TEST(TimerTest, sim_mode) {
  auto count = 0;

  auto func = [count]() { AINFO << count; };

  TimerOption to{1000, func, false};

  {
    Timer t;
    t.SetTimerOption(to);
    common::GlobalData::Instance()->EnableSimulationMode();
    t.Start();
    common::GlobalData::Instance()->DisableSimulationMode();
    t.Start();
    t.Start();
  }
}

}  // namespace timer
}  // namespace cyber
}  // namespace apollo

int main(int argc, char** argv) {
  testing::InitGoogleTest(&argc, argv);
  apollo::cyber::Init(argv[0]);
  return RUN_ALL_TESTS();
}
