name: Bazel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  baseline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Bazel
        run: sudo bash scripts/deps/install_bazel.sh
      - name: Run Ubuntu 22.04 baseline
        run: bash scripts/release/ubuntu2204_baseline.sh
